### ISSUE TITLE
no one .ino appears

### ISSUE THREAD

**Issue by Kyogre** [mycroftHo/miduino#1]
after executing miduino it just tells that:

This is a midi file
Single Track Midi File
Number of tracks = 1
Time division = 480
Successfuly Read Midi Header
Reading track
Track length = 5920
Meta Event
Length of meta event : 16
Meta Event
Length of meta event : 16

but I can't find .ino file

**Comment by boylejack** [comment]
Hi Roman,

It looks like the program is only reading the first two events in the midi
file and then stopping for some reason. Would you be able to send me the
midi file in question and I can take a look and maybe find the bug with my
code?

Regards,
Jack

**Comment by Kyogre** [comment]
the same going with any of midi files. That one exactly is 20tx fox: https://freemidi.org/download-658 , also tryed on https://freemidi.org/download-1490-evita-movie-themes

**Comment by boylejack** [comment]
OK I'll have a look and see what's going wrong. Will hopefully have a patch
to push soon.

**Comment by boylejack** [comment]
My apologies for the delay in responding fully to this. This bug has now been fixed.
